spring:
  application:
    name: turnosWebSocket
  datasource:
    url: jdbc:mysql://192.168.100.72:3306/turnos?useSSL=false&serverTimezone=UTC
    username: usermysql
    password: Jm@nuelms83
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
